### ISSUE TITLE
Alert Alex Crichton to the fork

### ISSUE THREAD

**Issue by npmccallum** [rust-mbedtls/mbedtls-src#2]
@alexcrichton FYI, this is a friendly fork of `openssl-src` for mbedtls. You obviously have a lot of copyright here and we want to do right by you. If you add copyright headers to `openssl-src` we'll merge them here. Also, if you see any problems not giving you enough credit here please alert us and we will fix them. We want to do right by you.

**Comment by alexcrichton** [comment]
👍 

Feel free to copy, that's the fun of open source :)
